### ISSUE TITLE
User friendly command line failure

### ISSUE THREAD

**Issue by sterlingbaldwin** [ESGF/esg-publisher#111]
Currently when you run esgpublish with no arguments you get 
```
-bash-4.1$ esgpublish
Traceback (most recent call last):
  File "/export/baldwin32/anaconda2/bin/esgpublish", line 4, in <module>
    __import__('pkg_resources').run_script('esgcet==3.4.3', 'esgpublish')
  File "/export/baldwin32/anaconda2/envs/esg-pub-exp/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/export/baldwin32/anaconda2/envs/esg-pub-exp/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/export/baldwin32/anaconda2/lib/python2.7/site-packages/esgcet-3.4.3-py2.7.egg/EGG-INFO/scripts/esgpublish", line 754, in <module>
    main(sys.argv[1:])
  File "/export/baldwin32/anaconda2/lib/python2.7/site-packages/esgcet-3.4.3-py2.7.egg/EGG-INFO/scripts/esgpublish", line 515, in main
    raise ESGPublishError("Must specify project with --project")
esgcet.exceptions.ESGPublishError: Must specify project with --project
```

This is somewhat non-friendly. The command line argument parser should really catch this and print the help message.

**Comment by tkettenba** [comment]
This issue may be closed. Now esgpublish prints the following

```
# esgpublish
usage: esgpublish [-h] [--test] [--set-replica] [--no-replica] [--esgmigrate] [--json JSON] [--data-node DATA_NODE] [--index-node INDEX_NODE] [--certificate CERT] [--project PROJ] [--cmor-tables CMOR_PATH]
                  [--autocurator AUTOCURATOR_PATH] --map MAP [MAP ...] [--config CFG] [--silent] [--verbose] [--no-auth] [--verify] [--version] [--xarray]
esgpublish: error: the following arguments are required: --map
```

Tested with 
```
# esgpublish --version
esgpublish v5.2.1
```

**Comment by sashakames** [comment]
Thanks @tkettenba
