### ISSUE TITLE
esgintialize incompatible with SQLAlchemy v1.3.0

### ISSUE THREAD

**Issue by sashakames** [ESGF/esg-publisher#145]
INFO       2019-03-12 15:35:22,812 Updating schema version directory to /usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet/schema_migration
Traceback (most recent call last):
  File "/usr/local/conda/envs/esgf-pub/bin/esginitialize", line 195, in <module>
    main(sys.argv[1:])
  File "/usr/local/conda/envs/esgf-pub/bin/esginitialize", line 120, in main
    values={'repository_path':repo_path})
  File "<string>", line 1, in <lambda>
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/sqlalchemy/sql/selectable.py", line 1915, in update
    **kwargs
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/sqlalchemy/sql/dml.py", line 762, in __init__
    self._whereclause = _literal_as_text(whereclause)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 4471, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 4457, in _literal_as
    return text_fallback(element)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 4501, in _no_text_coercion
    "extra": "%s " % extra if extra else "",
sqlalchemy.exc.ArgumentError: Textual SQL expression "repository_id='ESG-CET no..." should be explicitly declared as text("repository_id='ESG-CET no...")

**Comment by sashakames** [comment]
Need to test with Python3.  we have upgraded
