### ISSUE TITLE
esgtest_publish error

### ISSUE THREAD

**Issue by sashakames** [ESGF/esg-publisher#154]
This problem is low priority unless too many testing workflows depend on it.

```
(esgf-pub) [ames4@esgf-data2 ~]$ esgtest_publish 
Traceback (most recent call last):
  File "/usr/local/conda/envs/esgf-pub/bin/esgtest_publish", line 4, in <module>
    __import__('pkg_resources').run_script('esgcet==4.0.0b1', 'esgtest_publish')
  File "/usr/local/conda/envs/esgf-pub/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/conda/envs/esgf-pub/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/conda/envs/esgf-pub/lib/python3.7/site-packages/esgcet-4.0.0b1-py3.7.egg/EGG-INFO/scripts/esgtest_publish", line 27, in <module>
    sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
  File "/usr/local/conda/envs/esgf-pub/lib/python3.7/os.py", line 1027, in fdopen
    return io.open(fd, *args, **kwargs)
ValueError: can't have unbuffered text I/O
```

**Comment by cjphaha** [comment]
i have this error too

**Comment by cjphaha** [comment]
my error is
```bash
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/airflow", line 4, in <module>
    __import__('pkg_resources').run_script('apache-airflow==1.10.7', 'airflow')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apache_airflow-1.10.7-py3.7.egg/EGG-INFO/scripts/airflow", line 25, in <module>
    from airflow.configuration import conf
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apache_airflow-1.10.7-py3.7.egg/airflow/__init__.py", line 42, in <module>
    from airflow.models import DAG
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apache_airflow-1.10.7-py3.7.egg/airflow/models/__init__.py", line 21, in <module>
    from airflow.models.baseoperator import BaseOperator, BaseOperatorLink  # noqa: F401
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apache_airflow-1.10.7-py3.7.egg/airflow/models/baseoperator.py", line 43, in <module>
    from airflow.models.dag import DAG
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apache_airflow-1.10.7-py3.7.egg/airflow/models/dag.py", line 48, in <module>
    from airflow.models.dagbag import DagBag
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apache_airflow-1.10.7-py3.7.egg/airflow/models/dagbag.py", line 50, in <module>
    class DagBag(BaseDagBag, LoggingMixin):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apache_airflow-1.10.7-py3.7.egg/airflow/models/dagbag.py", line 80, in DagBag
    DAGBAG_IMPORT_TIMEOUT = conf.getint('core', 'DAGBAG_IMPORT_TIMEOUT')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apache_airflow-1.10.7-py3.7.egg/airflow/configuration.py", line 326, in getint
    return int(self.get(section, key, **kwargs))
ValueError: invalid literal for int() with base 10: '30.0'
```
