### ISSUE TITLE
esgf-pub errors

### ISSUE THREAD

**Issue by tiantdk** [ESGF/esg-publisher#210]
Hej I have been published several CMIP6 data in the past few months. But since last week, I followed the same routines as before to publish more CMIP6 data, I ran into problem: 
**esgpublish --no-create-cim --project cmip6 --map /esg/mapfiles/dhi2 --service fileservice**
WARNING    2023-04-19 11:12:02,250 Cannot import handler esgcet.config.cmip6_handler:CMIP6Handler for project cmip6
Traceback (most recent call last):
  File "/usr/local/conda/envs/esgf-pub/bin/esgpublish", line 783, in <module>
    main(sys.argv[1:])
  File "/usr/local/conda/envs/esgf-pub/bin/esgpublish", line 620, in main
    registerHandlers(projectName)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet/config/config.py", line 438, in registerHandlers
    register(projectRegistry, projectName, m, cls)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet/config/registry.py", line 148, in register
    registry.register(projectName, moduleName, className)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/esgcet/config/registry.py", line 101, in register
    m = sys.modules[moduleName]
KeyError: 'esgcet.config.cmip6_handler'

**Comment by tiantdk** [comment]
I found it was due to not-enough-memory on my server.
