### ISSUE TITLE
Support for multidimensional coordinates in mk_dataset_xarray.py

### ISSUE THREAD

**Issue by zequihg50** [ESGF/esg-publisher#245]
When testing publication of CORDEX data in which variables "lat" and "lon" are 2-dimensional, I encountered that the script [mk_dataset_xarray.py](https://github.com/ESGF/esg-publisher/blob/main/src/python/esgcet/mk_dataset_xarray.py) produces an error, likely because it assumes that these variables are 1-dimensional.

This could be fixed by changing to something like this [here](https://github.com/ESGF/esg-publisher/blob/3a105e283f7693e81da579c29a009272f22bed66/src/python/esgcet/mk_dataset_xarray.py#L59) and [here](https://github.com/ESGF/esg-publisher/blob/3a105e283f7693e81da579c29a009272f22bed66/src/python/esgcet/mk_dataset_xarray.py#L83):

```python
record["north_degrees"] = lat.values.max()
record["south_degrees"] = lat.values.min()
```

```python
record["east_degrees"] = lon.values.max()
record["west_degrees"] = lon.values.min()
```

Although this made the trick for me I'm not sure this solution is general enough.

Additional info:

```bash
$  esgpublish --version
esgpublish v5.2.4
```

**Comment by sashakames** [comment]
@zequihg50 Thanks for pointing this out, your solution might be more comprehensive than the current use of the 1-D bounds array.  Can you submit a PR?

**Comment by zequihg50** [comment]
Sure.

**Comment by meteorologist15** [comment]
I have also encountered this error. Here is the stacktrace:
```
Traceback (most recent call last):
  File "/esg/publishing/miniconda3/envs/esgf-pub/lib/python3.8/site-packages/esgcet/generic_netcdf.py", line 75, in mk_dataset
    out_json_data = mkd.get_records(map_json_data, scan_arg, self.json_file, user_project=self.proj_config)
  File "/esg/publishing/miniconda3/envs/esgf-pub/lib/python3.8/site-packages/esgcet/mk_dataset.py", line 414, in get_records
    self.update_metadata(self.dataset, scanobj)
  File "/esg/publishing/miniconda3/envs/esgf-pub/lib/python3.8/site-packages/esgcet/mk_dataset.py", line 374, in update_metadata
    self.handler.set_bounds(record, scanobj)
  File "/esg/publishing/miniconda3/envs/esgf-pub/lib/python3.8/site-packages/esgcet/mk_dataset_xarray.py", line 59, in set_bounds
    record["north_degrees"] = float(lat[-1])
  File "/esg/publishing/miniconda3/envs/esgf-pub/lib/python3.8/site-packages/xarray/core/common.py", line 156, in __float__
    return float(self.values)
TypeError: only size-1 arrays can be converted to Python scalars
```
I saw this potential solution using the NumPy vectorize function:
https://stackoverflow.com/questions/36680402/typeerror-only-length-1-arrays-can-be-converted-to-python-scalars-while-plot-sh

**Comment by sashakames** [comment]
A PR was merged to this branch `v5.2.5-proj` you may install form source and use that
