### ISSUE TITLE
Spurious error message on thredds reinit

### ISSUE THREAD

**Issue by pchengi** [ESGF/esg-publisher#41]
Version of ESGF: 2.4.5 devel
A successful data publish ends with a suspicious looking error message like below. It's misleading and potentially confusing.

INFO       2016-12-08 20:33:33,947 Reinitializing THREDDS server
Traceback (most recent call last):
  File "/usr/local/uvcdat/2.2.0/bin/esgpublish", line 4, in <module>
    __import__('pkg_resources').run_script('esgcet==3.0.1', 'esgpublish')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 743, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1498, in run_script
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/esgcet-3.0.1-py2.7.egg/EGG-INFO/scripts/esgpublish", line 579, in <module>
    main(sys.argv[1:])
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/esgcet-3.0.1-py2.7.egg/EGG-INFO/scripts/esgpublish", line 573, in main
    result = publishDatasetList(datasetNames, Session, publish=publish, thredds=thredds, las=las, parentId=parent, service=service, perVariable=perVariable, reinitThredds=threddsReinit, restInterface=restApi, schema=schema)
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/esgcet-3.0.1-py2.7.egg/esgcet/publish/publish.py", line 295, in publishDatasetList
    result = reinitializeThredds()
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/esgcet-3.0.1-py2.7.egg/esgcet/publish/thredds.py", line 1081, in reinitializeThredds
    raise ESGPublishError("Error reinitializing the THREDDS Data Server. Result=%s"%`reinitResult`)
esgcet.exceptions.ESGPublishError: Error reinitializing the THREDDS Data Server. Result='<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.8 - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 401 - </h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>This request requires HTTP authentication.</u></p><hr class="line"><h3>Apache Tomcat/8.5.8</h3></body></html>'

**Comment by cofinoa** [comment]
Prasha, 

the user been used to reinit the catalog doesn't have the requiered role to do it. 
http://www.unidata.ucar.edu/software/thredds/current/tds/reference/RemoteManagement.html

Antonio

**Comment by sashakames** [comment]
We think this is an issue with tomcat 8.5.8 in how the password is encoded.  Keeping the issue open until fixed in the installer

**Comment by pchengi** [comment]
Thanks @sashakames  and @cofinoa . The tomcat rollback made this issue go away, so closing this issue.
