### ISSUE TITLE
Publication fails with thredds reinit error

### ISSUE THREAD

**Issue by pchengi** [ESGF/esg-publisher#42]
Note: this is just to document an observed issue. I believe the issue to be closed. I'll update details here and close the issue -pchengi

Publication fails on fresh install of v2.4.11-devel-release with the following error trace.

Traceback (most recent call last):
  File "/usr/local/uvcdat/2.2.0/bin/esgpublish", line 4, in <module>
    __import__('pkg_resources').run_script('esgcet==3.0.1', 'esgpublish')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 739, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1494, in run_script
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/esgcet-3.0.1-py2.7.egg/EGG-INFO/scripts/esgpublish", line 579, in <module>
    main(sys.argv[1:])
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/esgcet-3.0.1-py2.7.egg/EGG-INFO/scripts/esgpublish", line 573, in main
    result = publishDatasetList(datasetNames, Session, publish=publish, thredds=thredds, las=las, parentId=parent, service=service, perVariable=perVariable, reinitThredds=threddsReinit, restInterface=restApi, schema=schema)
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/esgcet-3.0.1-py2.7.egg/esgcet/publish/publish.py", line 295, in publishDatasetList
    result = reinitializeThredds()
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/esgcet-3.0.1-py2.7.egg/esgcet/publish/thredds.py", line 1081, in reinitializeThredds
    raise ESGPublishError("Error reinitializing the THREDDS Data Server. Result=%s"%`reinitResult`)
esgcet.exceptions.ESGPublishError: Error reinitializing the THREDDS Data Server. Result='<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.39 - Error report</title><style type="text/css">H1
{font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3
{font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B
{font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px;
background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /thredds/admin/debug</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b>
<u>/thredds/admin/debug</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.0.39</h3></body></html>'

It was observed that thredds was failing to start.
Tomcat error logs contained this:
INFO: Initializing Spring root WebApplicationContext
Dec 21, 2016 4:54:44 PM org.apache.catalina.core.StandardContext filterStart
SEVERE: Exception starting filter authorizationFilter
java.lang.NoClassDefFoundError: org/apache/commons/collections/ExtendedProperties
        at org.apache.velocity.runtime.RuntimeInstance.<init>(RuntimeInstance.java:164)
        at org.apache.velocity.runtime.RuntimeSingleton.<clinit>(RuntimeSingleton.java:91)
        at org.apache.velocity.app.Velocity.setProperty(Velocity.java:122)
        at org.opensaml.DefaultBootstrap.initializeVelocity(DefaultBootstrap.java:122)
        at org.opensaml.DefaultBootstrap.bootstrap(DefaultBootstrap.java:86)
        at esg.security.common.SAMLBuilder.<clinit>(SAMLBuilder.java:171)
        at esg.security.authz.service.impl.SAMLAuthorizationServiceClientSoapImpl.<init>(SAMLAuthorizationServiceClientSoapImpl.java:61)
        at esg.orp.app.SAMLAuthorizer.<init>(SAMLAuthorizer.java:43)
        at esg.orp.app.SAMLAuthorizationServiceFilterCollaborator.<init>(SAMLAuthorizationServiceFilterCollaborator.java:46)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at esg.orp.app.AuthorizationFilter.init(AuthorizationFilter.java:85)
        at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4700)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5340)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections.ExtendedProperties

@soay observed that the installation logs complained about missing the deprecated commons-collections. When checked, these were the lines in the installation log:
cp: cannot stat `/usr/local/tomcat/webapps/esg-orp/WEB-INF/lib/commons-collections-3.2.1.jar': No such file or directory
cp: cannot stat `/usr/local/tomcat/webapps/OpenidRelyingParty/WEB-INF/lib/commons-collections-3.2.1.jar': No such file or directory
cp: cannot stat `/usr/local/tomcat/webapps/OpenidRelyingParty/WEB-INF/lib/xalan-2.7.1.jar': No such file or directory
cp: cannot stat `/usr/local/tomcat/webapps/OpenidRelyingParty/WEB-INF/lib/xercesImpl-2.9.1.jar': No such file or directory
cp: cannot stat `/usr/local/tomcat/webapps/OpenidRelyingParty/WEB-INF/lib/xml-apis-1.3.04.jar': No such file or directory

**Comment by pchengi** [comment]
commit 0728f8b3a07eba788940bfeffe258cf3913d5800 in esgf-installer is to fix this issue. The jar versions mentioned in esg-security-las-ip-filter were updated. This is expected to not only solve the thredds startup issue, but also the las startup issue. Will test and update this issue.

**Comment by sandipcccr** [comment]
I am also getting same error, while publication on new version of  ESGF 2.4.
The error is .....
-----
Traceback (most recent call last):
  File "/usr/local/uvcdat/2.2.0/bin/esgpublish", line 4, in <module>
    __import__('pkg_resources').run_script('esgcet==2.14.6', 'esgpublish')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 719, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1504, in run_script
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/esgcet-2.14.6-py2.7.egg/EGG-INFO/scripts/esgpublish", line 526, in <module>
    main(sys.argv[1:])
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/esgcet-2.14.6-py2.7.egg/EGG-INFO/scripts/esgpublish", line 508, in main
    datasets = iterateOverDatasets(projectName, dmap, directoryMap, datasetNames, Session, aggregateDimension, publishOp, filefilt, initcontext, offline, properties, keepVersion=keepVersion, newVersion=version, extraFields=extraFields, masterGateway=masterGateway, comment=message, readFiles=readFiles, nodbwrite=nodbwrite)
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/esgcet-2.14.6-py2.7.egg/esgcet/publish/utility.py", line 745, in iterateOverDatasets
    handler.validateContext(context)
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/esgcet-2.14.6-py2.7.egg/esgcet/config/project.py", line 537, in validateContext
    raise ESGPublishError("Invalid value of '%s': %s, must be one of %s"%(key, value, `validOptions`))
esgcet.exceptions.ESGPublishError: Invalid value of 'driving_model': IPSL-IPSL-CM5A-LR, must be one of ['CCCma-CanESM2', 'CNRM-CERFACS-CNRM-CM5', 'ECMWF-ERAINT', 'ERAINT', 'ICHEC-EC-EARTH', 'IPSL-IPSL-CM5A-MR', 'MIROC-MIROC5', 'MOHC-HadGEM2-ES', 'MPI-M-MPI-ESM-LR', 'MPI-M-MPI-ESM-MR', 'NCC-NorESM1-M', 'NOAA-GFDL-GFDL-ESM2M', 'CSIRO-QCCCE-CSIRO-Mk3-6-0', 'MOHC-HadGEM2-ES', 'IITM-RegCM4-1', 'IITM-RegCM4-4', '', None]

**Comment by soay** [comment]
This error is different and not related to the issue above.

Can you please make sure you have "IPSL-IPSL-CM5A-LR" in the list of your "driving_model_options", section "[project:cordex]", esg.ini or esg.cordex.ini?
In case you use a project specific ini file (esg.cordex.ini) you can fetch the most recent version with esgprep:

$ esgprep fetch-ini --project cordex

**Comment by sandipcccr** [comment]
Sorry, thank you soay, this issue was solved... i did mistake in pasting the error.

This is the error I am facing right now, while publication on new version of ESGF 2.4.

INFO       2017-02-22 16:34:46,945 Writing THREDDS catalog /esg/content/thredds/esgcet/2/cordex.output.WAS-44.IITM.CSIRO-QCCCE-CSIRO-Mk3-6-0.rcp45.r1i1p1.RegCM4-4.v5.sem.pr.v20170222.xml
INFO       2017-02-22 16:34:47,109 Writing THREDDS ESG master catalog /esg/content/thredds/esgcet/catalog.xml
INFO       2017-02-22 16:34:47,167 Reinitializing THREDDS server
Traceback (most recent call last):
  File "/usr/local/uvcdat/2.2.0/bin/esgpublish", line 4, in <module>
    __import__('pkg_resources').run_script('esgcet==3.0.1', 'esgpublish')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 719, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1504, in run_script
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/esgcet-3.0.1-py2.7.egg/EGG-INFO/scripts/esgpublish", line 579, in <module>
    main(sys.argv[1:])
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/esgcet-3.0.1-py2.7.egg/EGG-INFO/scripts/esgpublish", line 573, in main
    result = publishDatasetList(datasetNames, Session, publish=publish, thredds=thredds, las=las, parentId=parent, service=service, perVariable=perVariable, reinitThredds=threddsReinit, restInterface=restApi, schema=schema)
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/esgcet-3.0.1-py2.7.egg/esgcet/publish/publish.py", line 295, in publishDatasetList
    result = reinitializeThredds()
  File "/usr/local/uvcdat/2.2.0/lib/python2.7/site-packages/esgcet-3.0.1-py2.7.egg/esgcet/publish/thredds.py", line 1081, in reinitializeThredds
    raise ESGPublishError("Error reinitializing the THREDDS Data Server. Result=%s"%`reinitResult`)
esgcet.exceptions.ESGPublishError: Error reinitializing the THREDDS Data Server. Result='<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.9 - Error report</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style> </head><body><h1>HTTP Status 401 - </h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>This request requires HTTP authentication.</u></p><hr class="line"><h3>Apache Tomcat/8.5.9</h3></body></html>'
